SVG 컴포넌트 렌더링 이슈 관련 긴급 리팩터링
mju-likelion/mojito pull request #17
Opened 2023-02-24 18:55 UTC by harksu

변경사항

1. ABOUT 스크린 내 SVG -> PNG
2. ABOUT 스크린 내 필요한 데이터 객체 파일 분리( ABOUT_MJU_LIEKLIONS, ARTICELS)
3. FOOT PRINT 스크린 내 SVG -> PNG
### 
반드시 브랜치를 풀 받아서, 자신이 담당한 스크린에 관련 코드 및 스타일링을 점검해주시길 바랍니다.

커리큘럼 스크린은 아직 반영되지 않았기 때문에 리팩터링에서 제외하였습니다.

2023-02-24 18:58 UTC, harksu commented
제가 해당 이슈를 올바르게 이해한건지와 전부 제가 작성한 코드가 아니기 때문에, 꼭 풀받아서 점검 부탁드립니다.

긴급한 리팩터링이었다보니 꼼꼼하게 리뷰 부탁드려요.

2023-02-24 23:48 UTC, yhyem approved these changes
고생 많으셨습니다 👍 🥹🥹🥹 taks 넘겨 받아주셔서 너무 감사합니당..

2023-02-25 00:54 UTC, ChoiWonYu approved these changes
고생하셨습니다!!

2023-02-25 01:10 UTC, Bhanjo approved these changes
고생하셨습니다!

2023-02-25 07:27 UTC, ndaemy requested changes
bin 파일에는 커멘트가 안달려서 여기 달아둡니다.

`MobileProjectImages.png`, `TabletProjectImages.png`, `PcProjectImages.png` 파일에서 두 가지를 변경하면 좋을 것 같은데요,

1. ProjectImagesForMobile 이런 식으로 화면 사이즈를 suffix 로 빼면 어떨까요? 그래야 연관된 파일들끼리 알파벳순일 때 묶여있을 것 같습니다.
2. 아이폰 등의 고해상도 디바이스를 대응하기 위해 3x 정도로 export 하면 어떨까 싶어요! 당장 제 맥북부터 살짝 깨져보여서..

2023-02-25 07:27 UTC, ndaemy commented on src/pages/Main/About/AboutContent/AboutFileData.js
> +export const ARTICELS = [
오타있습니다 ARTICELS(X) ARTICLES(O)

2023-02-25 07:27 UTC, ndaemy commented
이걸 보면서 다른 파일들도 보게 됐는데, 여기서기 수정이 필요해보여서 조금 남겨봅니다

참고) 리뷰의 기준은 현 [develop 커밋](https://github.com/mju-likelion/mojito/blob/0dc8d7a21807d43e9a345cf6eb1aaa91cf987117)입니다

### 첫 배포 전에 반드시 해결되어야 할 것으로 보이는 문제
1. [Slogan.js](https://github.com/mju-likelion/mojito/blob/0dc8d7a21807d43e9a345cf6eb1aaa91cf987117/src/assets/images/Slogan.js) 를 보면 하나의 svg를 리사이징 하는 식으로 되어있는데, [피그마](https://www.figma.com/file/8nY4VVBpHAmAam2iQdkT7V/%EC%96%91%EC%A1%B0%EC%9E%A5?node-id=1455%3A8418&t=1o3XmqJLf6XAra7h-1)에 보면 하나의 svg를 리사이징 한 게 아니라 각기 다른 3개의 svg가 존재하고 있어요. 이거 각각의 svg import 하는 것으로 수정해야 할 것 같습니다.


### 리팩토링의 문제
1. [SvgComponent.js](https://github.com/mju-likelion/mojito/blob/0dc8d7a21807d43e9a345cf6eb1aaa91cf987117/src/components/SvgComponent.js) 파일은 파일명을 인자로 받아 해당 파일을 렌더링 하도록 되어있는데, 해당 파일이 존재하지 않을 경우 바로 앱 자체가 에러 터지게 됩니다. 추가로 IDE에서 파일을 추적하는 등의 도움을 받을 수도 없구요. 따라서 svg 파일을 import 받는게 나을 것 같아요. lazy loading 을 사용하려고 이랬던 것 같은데, babel에서 url-loader 나 file-loader 등을 통해서 해결해볼 수 있지 않을까 합니다. (결국 Next 가면 바로 `import Image from 'next/image';` 로 해결되어버리지만)

    - 추가로, 이미지를 lazy loading 한다는 개념이 여기에서 필요한지는 모르겠습니다. svg 파일은 그 자체로 html 코드인데, 이게 lazy loading 할 정도로 느린 녀석인지는 모르겠어요.

2. assets/images 에 존재하는 파일들 중에 svg 를 바로 반환하는데 굳이 React Component 로 만든 친구들이 조금 보입니다. 이 친구들은 svg 파일로 표현해도 괜찮지 않을까 싶어요. 아니면 아예 코딩 기조를 "모든 svg는 리사이징의 가능성이 있다고 가정한다" 라고 해버리고 모두 다 React Component로 가는 것도 방법이구요.

3. 메인 사이트 특성상 assets/images 폴더가 거대해지고 있는듯한데, 반복되어 사용되지 않는 컴퍼넌트들이 많으므로 어디에서 사용되는 에셋인지 폴더로 구별해줘도 괜찮겠다 싶네요.

4. 하나의 svg 가 여러 개로 리사이징 되어야 한다면, [이런 코드](https://github.com/mju-likelion/mojito/blob/0dc8d7a21807d43e9a345cf6eb1aaa91cf987117/src/pages/Main/FootPrint/index.js#L76-L87)로 짜보시면 어떨까요?

5. window.open을 통한 새 탭 열기는 사용하시지 않는걸 추천합니다. a 태그가 html 표준 링크이기도 하고, js 로 새 탭을 열게 되면 SEO 가 좋지 않습니다. 그리고 웹브라우저 내부에 있는 기술 중에 a태그가 있는 링크들을 미리 로딩하는 pre-loading 기술이 있는데, 이게 JS일 때 잘 작동할지도 의문이구요.

6. `<img />` 태그는 alt 속성이 a11y 관점에서 필수입니다. 나중에는 다 챙겨져야 할 것 같네요.

2023-02-25 07:49 UTC, Bhanjo commented
크 내가 고려하지 않은 부분도 찝어주는 예빈센세.. 감사합니다...

2023-02-25 14:28 UTC, harksu commented on src/pages/Main/About/AboutContent/AboutFileData.js
> +export const ARTICELS = [
..^^ 죄송합니다

2023-02-25 14:33 UTC, harksu commented
2차 리팩터링 들어가겠습니다.

1.슬로건 및 SvgComponents와 같은 경우는 우선 이번 풀리에서는 제외하고 추후에 @Bhanjo 굑팀장님이 리팩터링 해주시면 좋을 것 같아요(해당 코드 플로우를 기획 및 개발하신분이기 때문에 본인이 의도한 동작을 지키고자합니다.)

2. 2번 같은 경우는, 코드의 통일성 및 유지보수를 위해서 대부분의 흐름을 따라 ReactComponents로 변환을 한건데, 괜찮으시다면 유지보수의 용이성을 위해서 모든 SVG는 ReactComponents로 변환해서 사용하는걸로 하시는거 어떨까요? @Bhanjo @yhyem  @ChoiWonYu  @mywhzy 

3. 사실 이 작업을 새벽에 정말하고싶었다가 파일이 너무 많아서 불필요한 파일만 제거를 했는데 이 부분에 대해선 추후에 반드시 리팩터링하고 확장하는 방향으로 가야될 것 같습니다.

4. 이런 미친 제 코드를 멘션하시다뇨 영광입니다.

5. 까먹었네요.. 이건 수정하도록 하겠습니다

2023-02-25 14:36 UTC, harksu commented
> bin 파일에는 커멘트가 안달려서 여기 달아둡니다.
> 
> `MobileProjectImages.png`, `TabletProjectImages.png`, `PcProjectImages.png` 파일에서 두 가지를 변경하면 좋을 것 같은데요,
> 
> 1. ProjectImagesForMobile 이런 식으로 화면 사이즈를 suffix 로 빼면 어떨까요? 그래야 연관된 파일들끼리 알파벳순일 때 묶여있을 것 같습니다.
반영하도록 하겠습니당 
> 2. 아이폰 등의 고해상도 디바이스를 대응하기 위해 3x 정도로 export 하면 어떨까 싶어요! 당장 제 맥북부터 살짝 깨져보여서..

2023-02-25 14:38 UTC, harksu commented
@ndaemy  suffix 밑 화질 보정 반영하도록 하겠습니다

2023-02-25 15:45 UTC, harksu commented
작업내용 @ndaemy 

1. 오타수정
2. 발자국 관련 png 3x로 이미지 화질 변경
3. a태그 반영
4. 컴포넌트명 FootPrint -> Project
5. image폴더 분리(About,Project)
6. 이미지 컴포넌트 분리
7. alt추가

todo @Bhanjo 

1. about쪽 png 3x로 이미지 화질 변경(+ 컨테이너에 맞도록 이미지 크기 변경..?)
2. about쪽 a태그로 변경
3. about쪽 alt추가

2023-02-25 18:39 UTC, ChoiWonYu commented
수정 사항 모두 확인했습니다. 
svg를 ReactComponent로 통일하는 것 저는 동의합니다.
그럼 피드백 내용 중 저랑 공통되는 사항들 내일 바로 리팩터링하겠습니다!

2023-02-25 23:46 UTC, ndaemy approved these changes
수고 많으셨습니다!

### 추후 리팩토링 하면 좋을만한 것

1. 아래 이미지 피그마에 있는 원본화질 자체가 너무 낮아서, 나중에 고화질본으로 수정할 수 있으면 좋을 것 같아요
<img width="705" alt="image" src="https://user-images.githubusercontent.com/18691542/221384690-dd7b7209-23f7-44fe-9630-cee8a16cf786.png">

2023-02-26 02:42 UTC, merged