About 파트 반응형 웹 구현
mju-likelion/mojito pull request #5
Opened 2023-02-19 15:27 UTC by Bhanjo

[DONE]
- About likelion 파트 반응형 웹 구현

[TODO]
- About Mju 파트 반응형 웹 구현

2023-02-22 17:11 UTC, harksu requested changes

2023-02-22 17:11 UTC, harksu commented on src/pages/Main/About/index.js
> +        <Button text={'지원하기'} handleClick={() => window.open('https://mjulikelion-apply.netlify.app/', '_blank')} />
이거 링크 변경하셔야 됩니당 👍

2023-02-22 17:12 UTC, harksu commented on src/pages/Main/About/index.js
> +        <Button text={'지원하기'} handleClick={() => window.open('https://mjulikelion-apply.netlify.app/', '_blank')} />
나중에 변경해도 되지만, 혹시 잊어먹으실까봐 :) 이거 저희 CORS때문에 이 링크로 하면 안됩니다 :)

2023-02-23 06:36 UTC, Bhanjo commented on src/pages/Main/About/index.js
> +        <Button text={'지원하기'} handleClick={() => window.open('https://mjulikelion-apply.netlify.app/', '_blank')} />
아 맞다

2023-02-23 07:34 UTC, yhyem approved these changes
고생 많으셨습니다 👍👍👍

2023-02-23 07:34 UTC, yhyem commented on src/pages/Main/About/AboutContent/AboutMJU.js
> +
h1 은 따로 styled-components로 안 빼신 이유가 있을까요?

2023-02-23 07:34 UTC, yhyem commented on src/pages/Main/Banner/index.js
>  };
useWindowResize 렌더링 문제로 고민하고 계시다면 ResponsivbeBody 컴포넌트 사용도 괜찮을것 같습니다!
이미 제 브랜치에서 파일을 땡겨 오셨더라구요! 👍
제가 대충 짜보긴 했지만 요론 방식은 어떤지 생각한번 해주세욥!

```
import ResponsiveBody from '../../../components/ResponsiveBody';

const Banner = () => {
  return (
    <Container>
      <ResponsiveBody
        mobileText={<Slogan width={318} height={100} />}
        tabletText={<Slogan width={568} height={176} />}
        desktopText={<Slogan width={1200} height={370} />}
      />
    </Container>
  );
};
```

2023-02-23 07:37 UTC, yhyem commented on src/pages/Main/Banner/index.js
>  };
props 네이밍은 Text로 해놔서 조금 이상하긴 한데.. 이건 제가 나중에 손볼게요 💦💦💦

2023-02-23 08:22 UTC, yhyem commented on src/pages/Main/About/AboutContent/AboutLikelion.js
> +  margin: 0 56px 0 16px;
해빈언니 한테 물어봤는데 디자인 의도가 중앙정렬이라고 하셔서 
maring: 0 auto 로 변경되어야 할것 같습니다!! 
tablet 도 마찬가지로..!

2023-02-23 14:40 UTC, Bhanjo commented on src/pages/Main/Banner/index.js
>  };
props 네이밍 규칙이 안맞으니까 탈락

2023-02-23 14:41 UTC, Bhanjo commented on src/pages/Main/Banner/index.js
>  };
장난이고 이걸로 바꿀게요!

2023-02-23 14:41 UTC, Bhanjo commented on src/pages/Main/About/AboutContent/AboutLikelion.js
> +  margin: 0 56px 0 16px;
왠지 이상하다 했다

2023-02-23 14:53 UTC, Bhanjo commented on src/pages/Main/About/AboutContent/AboutMJU.js
> +
가장 큰 이유는 해당 h1 태그의 스타일은 Wapper에서만 사용하기 때문입니다!

만약 이 스타일이 동일 컴포넌트에 다른 곳에서도 쓰이거나 외부에서도 쓰이는 거라면 따로 styped-components로 구현하는 게 맞지만 이거는 Wapper 안에서 한 번만 쓰이고 다른 곳에서 쓰이지 않아 분리할 필요가 없다 생각했어요

때문에 오히려 분리하는게 가독성 측면에서 더 안좋다 결론이 났습니다!

요약하자면 종속되어있는 개념을 억지로 독립적으로 만들어서 더 혼란을 주는 것을 피하고 싶었어요

2023-02-23 15:32 UTC, yhyem commented on src/pages/Main/About/AboutContent/AboutMJU.js
> +
띵언. 좋은 말씀 입니다. 기억해둬야지 👍

2023-02-23 16:41 UTC, yhyem commented on src/pages/Main/Banner/index.js
>  /** @TODO hanjo: 모바일, 태블릿 스타일링 적용 필요 */
아직 슬로건 배경은 반응형은 구현 안된걸까욧?? 
화면크기에 따라 파란배경 높이요!

2023-02-24 01:34 UTC, Bhanjo commented on src/pages/Main/Banner/index.js
>  /** @TODO hanjo: 모바일, 태블릿 스타일링 적용 필요 */
파란배경 높이 생각을 못하고 있었네.. 퇴근하고 반영하겠습니다!

2023-02-24 04:28 UTC, ChoiWonYu approved these changes
고생하셨습니다 👍👍

2023-02-24 14:32 UTC, merged