모집 안내 퍼블리싱
mju-likelion/mojito pull request #7
Opened 2023-02-20 15:01 UTC by yhyem

*공통
글로벌 스타일링 color GRAY4 추가
화면 크기에 따른 display block/none 컴포넌트 ResponsiveBody 추가
타이틀 버튼 컴포넌트 추가
글로벌 폰트 Montserrat 굵기 500 추가

[DESKTOP]
![image](https://user-images.githubusercontent.com/65844764/220176261-b269ea6d-680f-44ed-8ac0-d1b82c35466c.png)
![image](https://user-images.githubusercontent.com/65844764/220176293-18d78d87-231e-49c7-bfe2-85726831c460.png)
![image](https://user-images.githubusercontent.com/65844764/220376347-79324213-8f2b-451a-a880-713094a026e2.png)
![image](https://user-images.githubusercontent.com/65844764/220376403-8c517eda-06ef-4f49-a7c2-6cdfda8ecef8.png)

[TABLET]
![image](https://user-images.githubusercontent.com/65844764/220176342-fb19c946-9e10-4f14-ac53-45fb06cd30e9.png)
![image](https://user-images.githubusercontent.com/65844764/220176381-8c43438c-83de-488c-b499-f26719d5faea.png)
![image](https://user-images.githubusercontent.com/65844764/220376496-73a630f1-3190-4225-88c0-bff2aaaeb4b1.png)

[MOBILE]
![image](https://user-images.githubusercontent.com/65844764/220176411-48a30f02-1915-485e-ba41-6302458b80e0.png)
![image](https://user-images.githubusercontent.com/65844764/220176448-ed5b9725-e4fb-4259-9134-775af74849c7.png)
![image](https://user-images.githubusercontent.com/65844764/220376676-8befd551-df70-4984-a14a-88a985167196.png)
![image](https://user-images.githubusercontent.com/65844764/220376722-f0a4317d-aeb6-440c-966b-c4605618a165.png)

2023-02-21 11:54 UTC, Bhanjo commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/PartImage.js
> +};
파트별로 다른 이미지를 이렇게 일반화 한거 굳bb

여기서 좀 더 일반화를 하면 제가 만든 SvgComponent가 됩니다! 나중에 리팩터링할 때 SvgComponent를 쓰는 것도 좋겠네요

2023-02-21 11:54 UTC, Bhanjo commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/MobileNoClick.js
> +};
파일 구조를 보면 같은 RecruitPart인데 Mobile과 Tablet이 다른 컴포넌트 단위로 구성되어있어요
즉, 관심사는 같은데 컴포넌트를 따로 만들어서 파일이 더 많아졌어요!

이걸 조금 묶어보자면

```
RecruitPart
ㄴ Mobile
ㄴ PartInfo
```
이렇게 만들고 Mobile 컴포넌트 안에

```
export const Mobile = () => {
  switch(viewType) {
    case '모바일': return <모바일 컴포넌트 />
    case '태블릿': return <태블릿 컴포넌트 />
  }
}

const 모바일컴포넌트 = () => {}
const 태블릿컴포넌트 = () => {}
```

이렇게 정리할 수 있겠네요

정답은 없으니까 마음에 드시는 방법을 쓰면 됩니다!

이 설계를 좀 더 발전시키자면 Click, noClick도 묶어줄 수 있으니까 시간날 때 한번 고민해보세요!

2023-02-21 11:54 UTC, Bhanjo commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/RecruitPart.js
> +  };
이건 컴포넌트가 리렌더링 될 떄마다 재선언 되는데 useCallback으로 최적화해보면 좋을 것 같습니다!
그리고 changeWidth의 경우 제가 useWindowResize 커스텀 hook을 만들었는데 아직 develop에 반영이 안됐어요 나중에 이걸 활용해보는 것도 좋아보입니다!

2023-02-21 15:19 UTC, harksu requested changes
👍

2023-02-21 15:19 UTC, harksu commented on src/components/ResponsiveBody.js
> +`;
어차피 둘다 속성이 같은데 미디어쿼리를 나눈 이유가 뭘까용?

2023-02-21 15:19 UTC, harksu commented on src/pages/Main/Recruit/RecruitContent/Culturefit/RecruitCulturefit.js
> +        ))}
첫 번째 매개변수가 c라고 나온 이유가 있을까요?

2023-02-21 15:19 UTC, harksu commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/PartInfo.js
> +  }
잘짰네요 👍  :god혜민:

2023-02-21 15:24 UTC, yhyem commented on src/components/ResponsiveBody.js
> +`;
왜나눴지?

2023-02-21 15:25 UTC, yhyem commented on src/pages/Main/Recruit/RecruitContent/Culturefit/RecruitCulturefit.js
> +        ))}
culturefitData라 c... 라고 했어요 저 map 쓸때마다 첫 스펠링 써서.. 가독성이 안좋군요

2023-02-21 15:39 UTC, yhyem commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/PartImage.js
> +};
나중에 머지하고 리팩토링 해봐야겠네용!!! 👍👍👍

2023-02-21 15:43 UTC, yhyem commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/MobileNoClick.js
> +};
오오... 역시 다양한 방법이 많이 있군요 더 공부해봐야겠어요 💦💦💦

2023-02-21 15:44 UTC, yhyem commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/RecruitPart.js
> +  };
이슈로 올려주신 그내용이군요! 요고 리팩토링하고 hook 적용도 해볼게요!

2023-02-21 15:50 UTC, yhyem commented on src/pages/Main/Recruit/RecruitContent/RecruitPart/RecruitPart.js
> +  };
요친구는 x-rated에서도 꼭 리팩토링 하고싶었던 친구라 제가 더 고민하면서 수정하게씁니다 👍👍 
어제 예빈오바와 구글밋하면서 얘기한 내용이 css로 활용하는 방법도 있다해서 ResponsiveBody 라는 공통 컴포넌트로 하나 만들어둬서 이친구도 활용해서 리팩토링 해보겠습니당!

2023-02-22 08:08 UTC, harksu approved these changes
👍

2023-02-22 08:26 UTC, Bhanjo approved these changes
고생하셨습니다!

2023-02-22 15:10 UTC, merged